{% set metview_version = "5.6.0" %}
{% set codes_ui_version = "1.2.3" %}

package:
  name: codes-ui
  version: {{ codes_ui_version }}

source:
  url: https://confluence.ecmwf.int/download/attachments/30048389/Metview-{{ metview_version }}-dev4-Source.tar.gz
  sha256: f0eee5fc7a546387af8b02cb345e7246f6611ecf55683cee2bdc37b3abba2ec5

build:
  number: 1003
  skip: True  # [(win and vc<14)]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('libxext') }}  # [linux]
  host:
    - eccodes
    - magics
    - qt
  run:
    - eccodes
    - magics
    - qt

test:
  commands:
    - conda inspect linkages -p $PREFIX codes-ui  # [not win]
    - conda inspect objects -p $PREFIX codes-ui  # [osx]

about:
  home: https://confluence.ecmwf.int/display/METV/CodesUI
  license: Apache 2.0
  license_family: Apache
  license_file: metview/src/codes_ui/LICENSE
  summary: ECMWF CodesUI Copyright 2007-2019 ECMWF.

extra:
  recipe-maintainers:
    - dtip
    - StephanSiemen
