{% set codes_ui_version = "1.3.3" %}

package:
  name: codes-ui
  version: {{ codes_ui_version }}

source:
  url: https://confluence.ecmwf.int/download/attachments/92333258/codes_ui-{{ codes_ui_version }}-Source.tar.gz
  sha256: c604956f4ab75c1ef1fae3df6f064c174194f09c8317fc0a1cb92675b84acc6e
  patches:


build:
  number: 0
  skip: True  # [(win and vc<14)]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('libxext') }}  # [linux]
    - m2-sed  # [win]
  host:
    - eccodes
    - qt >=5.12
    - zlib
  run:
    - eccodes
    - qt >=5.12
    - zlib

test:
  commands:
    - conda inspect linkages -p $PREFIX codes-ui  # [not win]
    - conda inspect objects -p $PREFIX codes-ui  # [osx]

about:
  home: https://confluence.ecmwf.int/display/METV/CodesUI
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: ECMWF CodesUI Copyright 2007-2020 ECMWF.

extra:
  recipe-maintainers:
    - dtip
    - StephanSiemen
    - iainrussell
    - sandorkertesz
