{% set codes_ui_version = "1.5.2" %}

package:
  name: codes-ui
  version: {{ codes_ui_version }}

source:
  url: https://confluence.ecmwf.int/download/attachments/92333258/codes_ui-{{ codes_ui_version }}-Source.tar.gz
  sha256: f400c04139a08969203c4c27c152388e1eda40a71a6004f1666708fe9d41aee2
  patches:


build:
  number: 1
  skip: True  # [(win and vc<14)]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('libxext') }}  # [linux]
    - m2-sed  # [win]
  host:
    - eccodes
    - qt-main >=5.12
    - zlib
  run:
    - eccodes
    - qt-main >=5.12
    - zlib

test:
  commands:

about:
  home: https://confluence.ecmwf.int/display/METV/CodesUI
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: ECMWF CodesUI Copyright 2007-2021 ECMWF.

extra:
  recipe-maintainers:
    - dtip
    - iainrussell
    - sandorkertesz
