{% set codes_ui_version = "1.2.7" %}

package:
  name: codes-ui
  version: {{ codes_ui_version }}

source:
  url: https://confluence.ecmwf.int/download/attachments/92333258/codes_ui-{{ codes_ui_version }}-Source.tar.gz
  sha256: fef993a90e7e22fb81227cd8067bd263d4fe97294cb561ae253e1a01ef28791b
  patches:
    - 0002-Minimum-CMake-version-of-3.6.0.patch

build:
  number: 1
  skip: True  # [(win and vc<14)]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('libxext') }}  # [linux]
  host:
    - eccodes
    - qt >=5.12
    - zlib
  run:
    - eccodes
    - qt >=5.12
    - zlib

test:
  commands:
    - conda inspect linkages -p $PREFIX codes-ui  # [not win]
    - conda inspect objects -p $PREFIX codes-ui  # [osx]

about:
  home: https://confluence.ecmwf.int/display/METV/CodesUI
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: ECMWF CodesUI Copyright 2007-2019 ECMWF.

extra:
  recipe-maintainers:
    - dtip
    - StephanSiemen
    - iainrussell
    - sandorkertesz
