travis:
  secure:
    BINSTAR_TOKEN: sbgl1LhsDZHAybTPYfR/roNZgnVHkua+JZRr/n1gxB2Bn8DYQ9DzxmiO3YZXXQzyoTZ1iPzViAiP3nUrOb1lVSjr8YQ1x4OOFDAR1QMSyuRoa39nnvioeaJj2wliH5zcmcfeTlzTE3FuNzHxLXMHPQq8pptZxg5X20SCOkRu40JEd7SRQkyKsHJ4ld8jr2Guh9Q7+24kI1ynznWpPMNNe5LOyX/7zJ/dCT1qirW2QPnqDrouub9VH8ehORGY30hiGz49Yt2LovAOxaWEbAQ1KfCbHgsqGfZXoYjIYGqD8JCEQpqDk8zaSlkda0ox82vSSorc10+dYnxNtNatOaa2Ac7mLzIRtNNRzA6q2GpRdtgC/3OQeZKqZrvgBLPxUzC//nxcRxEArMapGPgWcP3doUOz+4D5qQolo6zaaTm2jXTm5XGWvwlQ8KzPL4J7iqFV5m4BXfswtv+mGBJQLzcfJBxHFDQE8aUwOBouiUcs5O/JaU8Fz+V6wfLCHQclilZWB0n2ZR+kvClWxIf7E4Tb+sFukLNCBTCtNN3Uka4dY1JpEa4MamdGGvhaalaRGMfdR/8JsJ9dDFTLCC/P0rLy41X01d9feprFvcq9tI3mANFV214hQM33NNngppIWQSPZH3EvvZf0XGnydSKu0+F1rsYjUN1YEfrYhXEMy1zjCOY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
